C FILE: CIRCUMFERENCE.F
      SUBROUTINE CIRCUMFERENCE(A, R)
C
C     CALCULATE THE CIRCUMFERENCE OF ANY RADIUS CIRCLE
C
      REAL*8 R, A(1), PI
      PI = 3.1415
      A(1) = 2 * PI * R
      END
C END FILE CIRCUMFERENCE.F

